== Introduction

OGC Code Sprints experiment with emerging ideas in the context of geospatial Standards and help improve interoperability of existing Standards by experimenting with new extensions or profiles. They are also used for building proofs-of-concept to support standards development activities and the enhancement of software products. The nature of the activities is influenced by whether a code sprint is 'generic' or 'focused'. All OGC working groups are invited and encouraged to set up a thread in generic code sprints, whereas focused code sprints are tailored to a specific set of standards (typically limited to three standards).

In the case of MD stab=ndards hetergenous arrgh!

This ER presents the high-level architecture of the code sprint and describes each of the standards and software packages that were deployed in support of the code sprint. The ER also discusses the results and presents a set of conclusions and recommendations. The recommendations identify ideas for future work, some of which may be more appropriate for testbeds, pilots, or other types of OGC initiatives. Therefore, the reader is encouraged to consider the recommended future work within the context of all OGC Standards development, collaborative solutions, and innovation activities.

A lot of possible work items had been proposed as issues (https://github.com/opengeospatial/GeoDCAT-SWG/issues) in the GeoDCAT-SWG repository & as comments on one specific issue (https://github.com/opengeospatial/GeoDCAT-SWG/issues/17). With two developers in the room, two in the Americas and the promise of some joining from Europe, it emerged that the favourite topic areas were:
* alignment with PROV, either GeoDCAT & PROV (see https://github.com/opengeospatial/GeoDCAT-SWG/issues/18) or OGC API Records & PROV (see https://github.com/opengeospatial/GeoDCAT-SWG/issues/24)
* metadata for AI / OGC API Processes & Large Language Models (see https://github.com/opengeospatial/GeoDCAT-SWG/issues/18)
* ISO 19115-1 to (Geo)DCAT mapping (see https://github.com/opengeospatial/GeoDCAT-SWG/issues/17#issuecomment-2477907159, which could inform https://github.com/opengeospatial/GeoDCAT-SWG/issues/17#issuecomment-2376563378)

## Metadata for AI
Developers: (both in Sydney)
## Use of PROV in GeoDCAT & OGC API Record
Developers: 
See https://github.com/opengeospatial/GeoDCAT-SWG/issues/24
Could be as part of a OGC API Records GeoDCAT response (https://github.com/opengeospatial/GeoDCAT-SWG/issues/17#issuecomment-2434553700, https://github.com/opengeospatial/GeoDCAT-SWG/issues/17#issuecomment-2444035107, https://github.com/opengeospatial/GeoDCAT-SWG/issues/17#issuecomment-2477705703)

## ISO 19115-1 to GeoDCAT mapping
Developers: David (USA Pacific coast); Jeroen (Europe)

See https://github.com/opengeospatial/GeoDCAT-SWG/issues/17#issuecomment-2477907159, which could inform https://github.com/opengeospatial/GeoDCAT-SWG/issues/17#issuecomment-2376563378

ISO/TC 211 seems keen to publish an ISO 19115-1:2014 to GeoDCAT mapping during 2025; this could either be a Technical Specification ("normative" i.e. with requirements so it's possible to conform to) or a Technical Report (informative, no requirements etc, but a "line in the sand"). Either would then be revised when ISO 19115-1:2014 is revised (probably during 2026/2027) or when better consensus emerges on good practice.

Background:
A lot of 'prior art' exists, mapping from various editions of ISO 19115 (or at least subsets of them) to DCAT v2 or v3:
* W3C draft mapping from ISO 19115:2003 (unknown subset) to DCAT v2: [https://www.w3.org/2015/spatial/wiki/ISO_19115_-_DCAT_-_Schema.org_mapping ](https://www.w3.org/2015/spatial/wiki/ISO_19115_-_DCAT_-_Schema.html)
* EU mapping from ISO 19139 (encoding of ISO 19115:2003) (EU INSPIRE subset) to EU GeoDCAT-AP (an AP of DCAT v2): https://github.com/GeoCat/iso-19139-to-dcat-ap/blob/master/documentation/Mappings.md
* UK (draft) mapping from ISO 19115:2003 (EU INSPIRE subset) to DCAT v3: https://github.com/agiorguk/gemini/issues/41 (less detailed than above)
* implementations (XSLT) in GeoNetwork microservices e.g. https://github.com/geonetwork/geonetwork-microservices/tree/main/modules/services/ogc-api-records/src/main/resources/xslt/ogcapir/formats/copy for ISO 19115-1:2014 / ISO 19115-3 (UK / INSPIRE subset) to DCAT v3
